version: 0.2

phases:
  build:
    commands:
      - echo Install packages...
      - cd angular
      - npm install
      - echo Create build...
      - npm run build
      - echo Removing unnecessary files...
      - rm -rf node_modules/   
artifacts:
  files:
    - 'angular/dist/angular/*'
