version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages...
      - cd angular && npm install
  build:
    commands:
      - echo Create build...
      - cd angular && npm run build
  post_build:
    commands:
      - echo Removing unnecessary files...
      - cd angular && rm -rf node_modules/
artifacts:
  base-directory: './dist/angular'
  files:
    - '**/*'
